Emomar/urls.py
from django.urls import path
from django.contrib import admin
from Emomar import views
from django.conf import settings
from .views import HomeView
from django.conf.urls.static import static
from .views import ListeVisiteur_jourView
from Emomar.views import InformationsSupplementairesView

urlpatterns = [
    path('', views.Login, name='login-page'),
    path('accounts/register/', views.Register, name='register-page'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('home/', HomeView.as_view(), name='home'),
    path('Ajouter_visiteur/', views.AjouterVisiteurView.as_view(), name='Ajouter_visiteur'),
    path('Ajouter_sortie/', views.Ajouter_sortieView.as_view(), name='Ajouter_sortie'),
    path('table/liste_visiteur/',views. ListeVisiteurView.as_view(), name='liste_visiteur'),
    path('table/modifier_enregistrement/<int:enregistrement_id>/',views. ModifierEnregistrementView.as_view(), name='modifier_enregistrement'),
    path('liste_sortie/', views.ExitpageView.as_view(),name='liste_sortie'),
    path('liste_visiteur_jour/', ListeVisiteur_jourView.as_view(), name='liste_visiteur_jour'),
    path('informations_supplementaires/<int:pk>/', InformationsSupplementairesView.as_view(), name='informations_supplementaires'),
    
    path('admin/', admin.site.urls)

##layouts

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Version1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Emomar import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Emomar.urls')),
]
app_name = 'Emomar'
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Emomar/models.py
# Create your models here.
from django.db import models
from django.utils import timezone

class TypePieceIdentite(models.Model):
    nom = models.CharField(max_length=100)

    def __str__(self):
        return self.nom

class Enregistrement(models.Model):
    PIECE_IDENTITE = 'CIN'
    PERMIS_CONDUIRE = 'PC'
    PASSEPORT = 'PP'
    CARTE_BIOMÉTRIQUE = 'CB'
    CARTE_NINA = 'NINA'
    AUTRE = 'AU'

    TYPE_PIECE_CHOICES = [
    ('CIN', "Pièce d'identité"),
    ('PC', "Permis de conduire"),
    ('PP', "Passeport"),
    ('CB', "Carte biometrique"),
    ('NINA', "Carte nina"),
    ('AU', "Autre"),
    ]


    EnregistrementId = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    numero_telephone = models.CharField(max_length=15)
    Date_heure_entree = models.DateTimeField(default=timezone.now, null=False)
    lieu_visite = models.CharField(max_length=100)
    numero_badge = models.CharField(max_length=20)
    reference_piece = models.CharField(max_length=50)
    motif_visite = models.TextField()
    societe = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='photos/', null=True, blank=True)
    # Nouveau champ ajouté
    type_piece_identite = models.CharField(
        max_length=7,
        choices=TYPE_PIECE_CHOICES,
        default=PIECE_IDENTITE,
    )

    def save(self, *args, **kwargs):
        # Générer le numéro de badge avec des zéros ajoutés au début
        # en fonction de la longueur spécifiée (ici, 3 pour ajouter 3 zéros)
        self.numero_badge = str(self.numero_badge).zfill(3)

        super(Enregistrement, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.nom} {self.prenom} (ID: {self.EnregistrementId})"

class Sortie(models.Model):
    enregistrement = models.ForeignKey(Enregistrement, on_delete=models.CASCADE)
    Date_heure_sortie = models.DateTimeField(default=timezone.now, null=False, db_index=True)
    def get_photo_url(self):
        if self.enregistrement and self.enregistrement.photo:
            return self.enregistrement.photo.url
        return None

    def __str__(self):
        return f"Sortie de : {self.enregistrement.nom} {self.enregistrement.prenom} (Référence : {self.enregistrement.reference_piece}) à {self.Date_heure_sortie.strftime('%d %b %Y, %H:%M')} - Numéro de téléphone : {self.enregistrement.numero_telephone}, Numéro de badge : {self.enregistrement.numero_badge}"

# Récupérer tous les enregistrements
enregistrements = Enregistrement.objects.all()

# Créer une sortie pour chaque enregistrement
# Create your models here.

Emomar/forms.py
from django import forms
from .models import Sortie, Enregistrement
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, SetPasswordForm, PasswordResetForm, UsernameField
from django.contrib.auth.models import User
class EnregistrementcreateForm(forms.ModelForm):
    
    class Meta:
        model = Enregistrement
        fields = '__all__'

        
class SortieCreateForm(forms.ModelForm):
    class Meta:
          model = Sortie
          fields =['enregistrement', 'Date_heure_sortie']


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nom Utilisateur'
    }))
    password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Mot De Passe'
    }))

Emomar/views.py
from django.shortcuts import render, redirect, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from .models import Enregistrement,Sortie
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.db.models import Count
from django.utils import timezone
from django.http import JsonResponse
from django.views.generic.base import TemplateView
from django.views import View
from django.contrib import messages
from .models import Enregistrement,Sortie
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import  SortieCreateForm,EnregistrementcreateForm
from django.urls import reverse_lazy
from django.views.generic import RedirectView
import logging
from datetime import datetime 
from datetime import datetime, timedelta
from django.http import HttpResponseForbidden
import re
import calendar

# Create your views here.
@login_required

def Register(request):
    error_message = None

    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        name = request.POST.get('uname')
        email = request.POST.get('email')
        password = request.POST.get('pass')

        # Validation du format du mot de passe
        if not re.match(r'^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$', password):
            error_message = 'Le mot de passe doit contenir au moins 8 caractères avec des lettres et des chiffres.'
        else:
            try:
                new_user = User.objects.create_user(username=name, email=email, password=password)
                new_user.first_name = fname
                new_user.last_name = lname
                new_user.save()
                return redirect('login-page')
            except IntegrityError as e:
                print(f"Error: {e}")
                error_message = "Ce nom d'utilisateur est déjà utilisé. Veuillez en choisir un autre."

    return render(request, 'accounts/register.html', {'error_message': error_message})



def Login(request):
    error_message = None

    if request.method == 'POST':
        name = request.POST.get('uname')
        password = request.POST.get('pass')

        # Vérification du format du mot de passe
        if not re.match(r'^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$', password):
            error_message = 'Le mot de passe doit contenir au moins 8 caractères avec des lettres et des chiffres.'
        else:
            user = authenticate(request, username=name, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                error_message = 'Désolé, cet utilisateur n\'existe pas. Veuillez saisir vos informations correctement.'

    return render(request, 'accounts/login.html', {'error_message': error_message})


def logoutuser(request):
    logout(request)
    return redirect('login-page')


def test(request):
    return render(request, 'test.html', {})

class HomeView(View):
    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        current_date = timezone.now().date()

        # Calculer le début et la fin de l'année actuelle
        start_of_year = current_date.replace(month=1, day=1)
        end_of_year = current_date.replace(month=12, day=31)
        
        # Calculer le début et la fin de la semaine actuelle
        start_of_week = current_date - timedelta(days=current_date.weekday())
        end_of_week = start_of_week + timedelta(days=6)

        current_date = timezone.now().date()

        # Requête pour le nombre total de sorties depuis le début de l'année
        total_exits = Sortie.objects.filter(Date_heure_sortie__date__range=[start_of_year, current_date]).count()

        # Compter le nombre de sorties par jour (en fonction de la date)
        exits_per_day = Sortie.objects.filter(Date_heure_sortie__date=current_date).count()

        # Requête pour le nombre total d'entrées depuis le début de l'année
        total_entries = Enregistrement.objects.filter(Date_heure_entree__date__range=[start_of_year, current_date]).count()

        # Compter le nombre d'entrées par jour (en fonction de la date)
        entries_per_day = Enregistrement.objects.filter(Date_heure_entree__date=current_date).count()
        
        start_of_week = current_date - timedelta(days=current_date.weekday())
        end_of_week = start_of_week + timedelta(days=6)
        
        # Initialize a dictionary to store entries per day
        entries_per_days = {}
        exits_per_days = {}
        
        # Loop through each day of the week (Monday to Sunday)
        for day in range(7):
            # Calculate the start and end dates for the current day
            start_of_day = start_of_week + timedelta(days=day)
            end_of_day = start_of_day + timedelta(days=1)

            # Query the database for entries on the current day
            entries_count = Enregistrement.objects.filter(Date_heure_entree__date=start_of_day).count()
            exits_count = Sortie.objects.filter(Date_heure_sortie__date=start_of_day).count()

            # Store the entries count for the current day in the dictionary
            entries_per_days[start_of_day.strftime('%A')] = entries_count
            exits_per_days[start_of_day.strftime('%A')] = exits_count

        # Calculer le début et la fin du mois actuel
        start_of_month = current_date.replace(day=1)
        next_month = current_date.replace(day=28) + timedelta(days=4)
        end_of_month = next_month - timedelta(days=next_month.day)

        # Requête pour le nombre de sorties par mois
        exits_per_month = []
        entries_per_month = []
        months = []

        for month in range(1, 13):
            start_month = current_date.replace(month=month, day=1)
            end_month = start_month.replace(day=calendar.monthrange(start_month.year, start_month.month)[1])
            months.append(start_month.strftime("%b"))

            exits_per_month.append(Sortie.objects.filter(Date_heure_sortie__date__range=[start_month, end_month]).count())
            entries_per_month.append(Enregistrement.objects.filter(Date_heure_entree__date__range=[start_month, end_month]).count())

        # Requête pour le nombre d'entrées par semaine
        entries_per_week = Enregistrement.objects.filter(Date_heure_entree__date__range=[start_of_week, end_of_week]).count()

        # Requête pour le nombre de sorties par semaine
        exits_per_week = Sortie.objects.filter(Date_heure_sortie__date__range=[start_of_week, end_of_week]).count()

        context = {
            'parent': 'dashboard',
            'segment': 'dashboardv1',
            'total_entries': total_entries,
            'total_exits': total_exits,
            'entries_per_day': entries_per_day,
            'entries_per_days': entries_per_days,
            'exits_per_day': exits_per_day,
            'exits_per_days': exits_per_days,
            'entries_per_week': entries_per_week,
            'exits_per_week': exits_per_week,
            'entries_per_month': entries_per_month,
            'exits_per_month': exits_per_month,
            'months': months,
        }

        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)
    
class ListeVisiteur_jourView(View):
    template_name = 'pages/tables/liste_visiteur_jour.html'

    def get(self, request, *args, **kwargs):
        today = datetime.now().date()

        # Filtrer les enregistrements pour la journée actuelle
        enregistrements = Enregistrement.objects.filter(Date_heure_entree__date=today).order_by('-Date_heure_entree')

        total_entries = enregistrements.count()

        context = {
            'enregistrements': enregistrements,
            'total_entries': total_entries,
        }

        return render(request, self.template_name, context)
logger = logging.getLogger(__name__)

class InformationsSupplementairesView(View):
    def get(self, request, pk):
        try:
            visiteur = get_object_or_404(Enregistrement, pk=pk)

            data = {
                'nom': visiteur.nom,
                'prenom': visiteur.prenom,
                'numero_telephone': visiteur.numero_telephone,
                'Date_heure_entree': visiteur.Date_heure_entree.strftime("%Y-%m-%d %H:%M:%S"),
                'lieu_visite': visiteur.lieu_visite,
                'numero_badge': visiteur.numero_badge,
                'reference_piece': visiteur.reference_piece,
                'motif_visite': visiteur.motif_visite,
                'societe': visiteur.societe,
                'type_piece_identite': visiteur.get_type_piece_identite_display(),
                'photo_url': visiteur.photo.url if visiteur.photo else None,
            }

            return JsonResponse(data)
        except Exception as e:
            logger.error(f"Erreur dans InformationsSupplementairesView: {e}")
            return JsonResponse({'error': 'Une erreur s\'est produite.'}, status=500)

class AjouterVisiteurView(View):
    template_name = 'pages/forms/Ajouter_visiteur.html'

    def get(self, request, *args, **kwargs):
        # Ajoutez ici le code pour obtenir le nombre total d'entrées
        total_entries = Enregistrement.objects.count()
        
        context = {
            'total_entries': total_entries
        }

        return render(request, self.template_name, context)

Emomar/templates/pages/tables/informations-supplementaires.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
    Informations Supplémentaires
{% endblock title %}

{% block extrastyle %}
    <!-- Ajoutez ici les liens vers les feuilles de style supplémentaires si nécessaire -->
{% endblock extrastyle %}

{% block bodyclass %}
    <!-- Ajoutez ici des classes CSS supplémentaires pour le corps de la page si nécessaire -->
{% endblock bodyclass %}

{% block content %}
    <!-- Contenu de la page -->
    <div class="container mt-5">
        <h2>Informations Supplémentaires</h2>
        <div class="row">
            <div class="col-md-6">
                <dl class="row">
                    <dt class="col-sm-4">Nom :</dt>
                    <dd class="col-sm-8">{{ nom }}</dd>

                    <dt class="col-sm-4">Prénom :</dt>
                    <dd class="col-sm-8">{{ prenom }}</dd>

                    <dt class="col-sm-4">Téléphone :</dt>
                    <dd class="col-sm-8">{{ numero_telephone }}</dd>

                    <dt class="col-sm-4">Date et heure d'entrée :</dt>
                    <dd class="col-sm-8">{{ Date_heure_entree }}</dd>

                    <dt class="col-sm-4">Lieu de visite :</dt>
                    <dd class="col-sm-8">{{ lieu_visite }}</dd>

                    <dt class="col-sm-4">Numéro de badge :</dt>
                    <dd class="col-sm-8">{{ numero_badge }}</dd>

                    <dt class="col-sm-4">Référence de pièce :</dt>
                    <dd class="col-sm-8">{{ reference_piece }}</dd>

                    <dt class="col-sm-4">Motif de visite :</dt>
                    <dd class="col-sm-8">{{ motif_visite }}</dd>

                    <dt class="col-sm-4">Société :</dt>
                    <dd class="col-sm-8">{{ societe }}</dd>

                    <dt class="col-sm-4">Type de pièce d'identité :</dt>
                    <dd class="col-sm-8">{{ type_piece_identite }}</dd>
                </dl>
            </div>
            <div class="col-md-6">
                {% if photo_url %}
                    <img src="{{ photo_url }}" alt="Photo" class="img-fluid">
                {% else %}
                    <p>Pas de photo disponible</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_scripts %}
    <!-- Ajoutez ici des scripts supplémentaires si nécessaire -->
{% endblock extra_scripts %}

Emomar/templates/pages/tables/modifier_enregistrement.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} Advanced Form Elements {% endblock title %}
{% block extrastyle %}
 <!-- daterange picker -->
 <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
 <!-- iCheck for checkboxes and radio inputs -->
 <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
 <!-- Bootstrap Color Picker -->
 <link rel="stylesheet" href="{% static 'plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css' %}">
 <!-- Tempusdominus Bootstrap 4 -->
 <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
 <!-- Select2 -->
 <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
 <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
 <!-- Bootstrap4 Duallistbox -->
 <link rel="stylesheet" href="{% static 'plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">
 <!-- BS Stepper -->
 <link rel="stylesheet" href="{% static 'plugins/bs-stepper/css/bs-stepper.min.css' %}">
 <!-- dropzonejs -->
 <link rel="stylesheet" href="{% static 'plugins/dropzone/min/dropzone.min.css' %}">
{% endblock extrastyle %}
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card">
        <div class="card-header">Formulaire d'Enregistrement</div>
        <div class="card-body">
          <form method="post" id="modification-form" enctype="multipart/form-data">
                {% csrf_token %}

                <h6 class="heading-small text-muted mb-4">Visiteur information</h6>
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label" for="id_prenom">Prénom</label>
                                <input type="text" id="id_prenom" name="prenom" class="form-control" placeholder="Prénom" value="{{ enregistrement.prenom }}">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label" for="id_nom">Nom</label>
                                <input type="text" id="id_nom" name="nom" class="form-control" placeholder="Nom" value="{{ enregistrement.nom }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label" for="id_numero_telephone">Numero téléphone</label>
                                <input type="tel" id="id_numero_telephone" name="numero_telephone" class="form-control" placeholder="Numero téléphone" value="{{ enregistrement.numero_telephone }}">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label" for="id_Date_heure_entree">Date et heure d'entrée</label>
                                <input type="datetime-local" id="id_Date_heure_entree" name="Date_heure_entree" class="form-control" value="{{ enregistrement.Date_heure_entree|date:'Y-m-d\TH:i:s' }}">
                            </div>
                        </div>
                    </div>
                </div>

                <hr class="my-4" />
                <h6 class="heading-small text-muted mb-4">Information sur son identité</h6>
                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-control-label" for="id_lieu_visite">Lieu de visite</label>
                                <input type="text" id="id_lieu_visite" name="lieu_visite" class="form-control" placeholder="Lieu de visite" value="{{ enregistrement.lieu_visite }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-control-label" for="id_numero_badge">Numero de Badge</label>
                                <input type="text" id="id_numero_badge" name="numero_badge" class="form-control" placeholder="Numero de Badge" value="{{ enregistrement.numero_badge }}">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-control-label" for="id_type_piece_identite">Type de pièce d'identité</label>
                                <select name="type_piece_identite" id="id_type_piece_identite" class="form-control">
                                    <option value="PI" {% if enregistrement.type_piece_identite == "PI" %}selected{% endif %}>Pièce d'identité</option>
                                    <option value="PC" {% if enregistrement.type_piece_identite == "PC" %}selected{% endif %}>Permis de conduire</option>
                                    <option value="PP" {% if enregistrement.type_piece_identite == "PP" %}selected{% endif %}>Passeport</option>
                                    <option value="CB" {% if enregistrement.type_piece_identite == "CB" %}selected{% endif %}>Carte biometrique</option>
                                    <option value="CN" {% if enregistrement.type_piece_identite == "CN" %}selected{% endif %}>Carte nina</option>
                                    <option value="AU" {% if enregistrement.type_piece_identite == "AU" %}selected{% endif %}>Autre</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-control-label" for="id_reference_piece">Reference de la pièce</label>
                                <input type="text" id="id_reference_piece" name="reference_piece" class="form-control" placeholder="Reference de la pièce" value="{{ enregistrement.reference_piece }}">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="pl-lg-4">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-control-label" for="id_societe">Société</label>
                                <input type="text" id="id_societe" name="societe" class="form-control" placeholder="Société" value="{{ enregistrement.societe }}">
                            </div>
                        </div>
                    </div>
                </div>

                <hr class="my-4" />
                <h6 class="heading-small text-muted mb-4">Motif de visite</h6>
                <div class="pl-lg-4">
                    <div class="form-group">
                        <label class="form-control-label" for="id_motif_visite">Motif de visite</label>
                        <textarea rows="4" id="id_motif_visite" name="motif_visite" class="form-control" placeholder="Motif de visite">{{ enregistrement.motif_visite }}</textarea>
                    </div>
                </div>
                <label for="photo">Sélectionnez une photo :</label>
                <input type="file" name="photo" id="photo" accept="image/*" required value="{{ enregistrement.photo }}">        
                

                <div class="col-7 text-right">
                  <input class="btn btn-primary" type="button" value="Modifier" style="font-size: 15px;" onclick="confirmModification()">
              </div>
                
            </form>

            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.errors }}
                </div>
            {% endif %}
        </div>
    </div>
</div>
</div>
</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

<script>
  function confirmModification() {
      // Afficher la boîte de dialogue de confirmation
      Swal.fire({
          title: "Es-tu sûr?",
          text: "Vous ne pourrez pas revenir en arrière!",
          icon: "question", // Utilisation de l'icône de question pour le point d'interrogation
          showCancelButton: true,
          confirmButtonColor: "#3085d6",
          cancelButtonColor: "#d33",
          confirmButtonText: "Oui, modifier!"
      }).then((result) => {
          // Si l'utilisateur a confirmé, redirigez vers la page de modification
          if (result.isConfirmed) {
              // Afficher un message de succès
              Swal.fire({
                  title: "Modifié!",
                  text: "Votre fichier a été modifié.",
                  icon: "success",
                  timer: 1000, // Durée d'affichage du message en millisecondes (1 seconde)
                  showConfirmButton: false // Cacher le bouton "OK" pour éviter la fermeture manuelle
              });
              // Ajouter un délai avant de soumettre le formulaire
              setTimeout(() => {
                document.getElementById('modification-form').submit();
              }, 1000); // Délai en millisecondes (1000 ms = 1 seconde)
          }
      });
  }
</script>





{% endblock content %}
{% block extra_scripts %}
<!-- jQuery -->
<!-- Select2 -->
<script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static 'plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js' %}"></script>
<!-- InputMask -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/inputmask/jquery.inputmask.min.js' %}"></script>
<!-- date-range-picker -->
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- bootstrap color picker -->
<script src="{% static 'plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js' %}"></script>
<!-- Bootstrap Switch -->
<script src="{% static 'plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- BS-Stepper -->
<script src="{% static 'plugins/bs-stepper/js/bs-stepper.min.js' %}"></script>
<!-- dropzonejs -->
<script src="{% static 'plugins/dropzone/min/dropzone.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>


<!-- Page specific script -->

{% endblock extra_scripts %}